### PR TITLE
Update versions + gitignore enhancement

### PR DESCRIPTION
**Pull request by gaborgsomogyi**

### CODE REVIEW

**Comment by gaborgsomogyi** [comment]
cc @HeartSaVioR

**Comment by HeartSaVioR** [comment]
Thanks @gaborgsomogyi ! I assume you've built with the change locally, right?

**Comment by gaborgsomogyi** [comment]
Yeah, sbt assembly passed.

**Comment by HeartSaVioR** [comment]
Nice! Thanks for your contribution!

**Comment by gaborgsomogyi** [comment]
Thanks for taking care!

**Pull request merged**
